---
- name: Install avahi-package
  apt:
    name: [ 'avahi-daemon' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes

- name: Generiere /etc/avahi/services/ssh.services
  template:
    src: "ssh.service.j2"
    dest: "/etc/avahi/services/ssh.services"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'ssh' in services"
  notify: restart avahi-daemon

- name: Generiere /etc/avahi/services/sftp-ssh.services
  template:
    src: "sftp-ssh.service.j2"
    dest: "/etc/avahi/services/sftp-ssh.services"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'ssh' in services"
  notify: restart avahi-daemon

- name: Generiere /etc/avahi/services/smb.services
  template:
    src: "smb.service.j2"
    dest: "/etc/avahi/services/smb.services"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'samba' in services"
    - samba is defined
  notify: restart avahi-daemon