---
- name: Install avahi-package
  apt:
    name: [ 'avahi-daemon' ]
    state: present
    update_cache: no
  become: yes

- name: Generiere /etc/avahi/services/ssh.services
  template:
    src: "ssh.service.j2"
    dest: "/etc/avahi/services/ssh.services"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'ssh' in services"
  notify: restart avahi-daemon

- name: Generiere /etc/avahi/services/sftp-ssh.services
  template:
    src: "sftp-ssh.service.j2"
    dest: "/etc/avahi/services/sftp-ssh.services"
    owner: root
    group: root
    mode: '0644'
  become: yes
  when:
    - "'ssh' in services"
  notify: restart avahi-daemon